import React, { useEffect } from 'react';
import { Abouts } from './About.styles';
import {ReactComponent as CloseSvg} from "../../images/add-sharp.svg";

export const About = () => {
    useEffect(() => {
        const tape = document.querySelector('.tape');
        const cloneItems = tape.innerHTML;
        tape.innerHTML += cloneItems; 

        const tapeContainer = document.querySelector('.tape-container');
        const tapeWidth = tape.scrollWidth;
        const animation = () => {
            if (tapeContainer.scrollLeft >= tapeWidth) {
                tapeContainer.scrollLeft = 0; 
            } else {
                tapeContainer.scrollLeft++; 
            }
        };
        const intervalId = setInterval(animation, 20); 
        return () => clearInterval(intervalId);
    }, []);
    
    return (
        <Abouts>
        <div className='thumb-about'>
        <h2 className='title-about'>a Story that started with <span className='title-abouts'> one simple ape</span> </h2>
        <p className='note1'>WHO GOT <br/>FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT</p>
        <p className='note2'> <CloseSvg className="close" width={24} height={24}/>EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE RANDOMLY GENERATED BY USERS</p>
        <span className="abouts-avatar" />
        </div>
        <div className='tape-container'>
        <ul className='tape'><li>Destroy stereotypes</li>
        <li><CloseSvg className="close" width={36} height={36}/></li>
        <li>HAVE NO LIMITS</li>
        <li><CloseSvg className="close" width={36} height={36}/></li>
        <li>Break rules</li>
        <li><CloseSvg className="close" width={36} height={36}/></li>
        </ul>
        </div>
        </Abouts>
        
    );
};